PathPlanner:
  rrt:
    # random sample points
    sample_points: 1500
    # max distance between sample points
    sample_max_d: 30.0

  rrt_star:
    # random sample points
    sample_points: 1500
    # max distance between sample points
    sample_max_d: 30.0
    # optimization radius
    optimization_r: 20.0

  rrt_connect:
    # random sample points
    sample_points: 1500
    # max distance between sample points
    sample_max_d: 30.0

  informed_rrt:
    # random sample points
    sample_points: 1500
    # max distance between sample points
    sample_max_d: 30.0
    # optimization radius
    optimization_r: 20.0
  
  quick_informed_rrt:
    # random sample points
    sample_points: 3000
    # max distance between sample points
    sample_max_d: 30.0
    # optimization radius
    optimization_r: 20.0
    # radius of priority circles set
    prior_circle_set_r: 15.0
    # increased distance of adaptive extend step size
    step_extend_d: 30.0 # suggest between half and one times sample_max_d
    # parallel rewire process
    rewire_threads_num: 4
    # aggressive or gradual optimizing strategy
    t_distr_freedom: 1.0 # suggest from 0.2 to 3